### ISSUE TITLE
Information regarding the Master Data of SCM module of the Oracle ERP

### ISSUE THREAD

**Issue by izuku-roy** [izuku-roy/Oracle-World-by-Izuku#2]
Give some information regarding the master data in the SCM module of the Oracle ERP

**Comment by shiladityaroy212** [comment]
Please assign me this issue

**Comment by izuku-roy** [comment]
Okay sure. Happy contributing!!

Regards
Abhradip

**Comment by shiladityaroy212** [comment]
I have contributed on this issue. Please check it

Regards
Shiladitya
