### ISSUE TITLE
Information regarding the Inventory Management of SCM module of the Oracle ERP

### ISSUE THREAD

**Issue by izuku-roy** [izuku-roy/Oracle-World-by-Izuku#3]
Give some information regarding the inventory management of the SCM module of the Oracle ERP

**Comment by shiladityaroy212** [comment]
Please assign me this issue.

**Comment by izuku-roy** [comment]
Okay sure. Happy contributing!!

Regards
Abhradip

**Comment by shiladityaroy212** [comment]
I have worked on this issue.Please check it and close the same

Regards
Shiladitya
